### ISSUE TITLE
remove qty from free product in cart

### ISSUE THREAD

**Issue by uncenteredDiv** [fullbl/Magento-Productcoupon#1]
Nice Extension, works out of the box!

But I got one question:
Is it possible to remove the qty in the cart for the free product?
Is there any variable I can use for a condition to find out if a product is free or not?

**Comment by fullbl** [comment]
Actually the quantity is forced to 1, no matter what. 

A possibility could be to find a way to save the same product in different items in cart (I did a little research, it should be possible), so we have one item that is the real product and another that is the free one.

I'll look into it in the next weeks!

**Comment by fullbl** [comment]
Hello, now quote item for free product has a custom option ('free' = 'true'), so a customer can buy another product of the same type. Max quantity for free product is still 1!
