### ISSUE TITLE
Error if promo product (regular price) is already in the cart

### ISSUE THREAD

**Issue by uncenteredDiv** [fullbl/Magento-Productcoupon#2]
Tried to apply the free product coupon code when the promo product with the regular price is already in the cart.

Got the following error:
**Fatal error: Uncaught Error: Call to a member function setQty() on boolean in /magento/app/code/community/Full/Productcoupon/Model/Observer.php:29 Stack trace: #0 /magento/app/code/core/Mage/Core/Model/App.php(1358): Full_Productcoupon_Model_Observer->addFreeProduct(Object(Varien_Event_Observer)) #1 /magento/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Full_Productcoupon_Model_Observer), 'addFreeProduct', Object(Varien_Event_Observer)) #2 /magento/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('checkout_cart_c...', Array) #3 /magento/app/code/community/Full/Productcoupon/controllers/CartController.php(51): Mage::dispatchEvent('checkout_cart_c...', Array) #4 /magento/app/code/core/Mage/Core/Controller/Varien/Action.php(41 in /magento/app/code/community/Full/Productcoupon/Model/Observer.php on line 29**

Is it possible to apply the coupon code after I added the promo product and the product price will be set to 0?

**Comment by fullbl** [comment]
That's strange, actually it should take the real product and set its price to 0!

Again, I'll check in next weeks!
